# Basic Site Settings
title: "Media Stacks International"  # The title of your site, shown in search results
description: "A brief description of your website for SEO purposes."
url: "https://mediastacks.co.uk"  # Your site's URL (replace with your actual URL)
baseurl: ""  # Leave empty if your site is hosted at the root level

# SEO Settings
seo:
  author: "Sian Breward"  # Author's name
  og_image: "/images/logo.png"  # Open Graph image for social sharing

# URL Settings
permalink: /:pretty  # Clean URLs, without .html (e.g., /about/ instead of /about.html)

# Markdown Processor
markdown: kramdown  # The Markdown processor used by Jekyll

# Theme (can be a Jekyll theme or a custom theme)
theme: css/style.css  # Jekyll's default theme, change to your own theme if desired

# Exclude Files from the Site
exclude:
  - README.md  # Exclude README file
  - Gemfile.lock  # Exclude Gemfile lock file

# Customizable Header and Footer (Optional)
header: "Media Stacks International"  # Custom header message (optional)
footer: ""  # Custom footer message (optional)

# Other Configurations (Optional)
markdown_ext: "md"  # Default markdown file extension
